### ISSUE TITLE
What should be done with obsolete classes?

### ISSUE THREAD

**Issue by caufieldjh** [Knowledge-Graph-Hub/kg-phenio#15]
Obsolete classes, and specifically obsolete phenotypes, are present as nodes in the graph.
Should they be removed after the fact?

**Comment by matentzn** [comment]
Good question: I think they are noise and should be removed. I would be interested to know though if you find any cases where an obsolete class is connected to another node..

**Comment by caufieldjh** [comment]
I found >14K edges involving obsoletes, though about 4600 of those are IAO:0100001 "term replaced by" edges - those probably aren't helping much.

**Comment by matentzn** [comment]
Yeah this can be quite misleading I think.. I would drop all obsolete classes.

**Comment by justaddcoffee** [comment]
On a related note, KGX nearly has support for throwing out obsolete classes using node filters - I say nearly, because if I am reading the code correctly [here](https://github.com/biolink/kgx/blob/b4e1e5ec3299885d1834d9a04b9f07f38690feae/kgx/utils/kgx_utils.py#L714), nodes can only be filtered by "category". 

I wonder if Sierra could comment on how hard it would be to add support for filtering on arbitrary columns/node properties

**Comment by caufieldjh** [comment]
The fix implemented here should be propagated as needed to other KG-Hub repos
